### ISSUE TITLE
rename yegg-test to dev test

### ISSUE THREAD

**Issue by Yegg12** [Yegg12/HolyCS#8]
dont do this you fucking, lets discuss this first

**Comment by Yegg12** [comment]
very good discussion, you have changed my mind about the entire subject and i thank you greatly.

**Comment by nonparallel** [comment]
lol ok

**Comment by Yegg12** [comment]
@nonparallel

**Comment by nonparallel** [comment]
@Yegg12

**Comment by nonparallel** [comment]
gonna assign myself and do it instead

**Comment by nonparallel** [comment]
done, closed.

**Comment by Yegg12** [comment]
i told you to discuss first damn

**Comment by nonparallel** [comment]
you dont have to reopen the issue lol
